

i.Display student names along with the department name.
SELECT NAME , DEPTNAME FROM STUDENT2053, DEPARTMENT2053
WHERE STUDENT2053.DEPTCODE = DEPARTMENT2053.DEPTCODE;




ii.Display student names, subject code and marks of students who took admission in the year 2017 and read subject CS502.
SELECT NAME, SUB_CODE, MARKS
FROM STUDENT2053 , RESULT2053
WHERE STUDENT2053.YEAROFADM=2017 AND STUDENT2053.ROLLNO = RESULT2053.ROLLNO AND RESULT2053.SUB_CODE='CS502';



iii.Find the name of the students who got marks between 70 to 89 in CS501.
SELECT NAME
FROM STUDENT2053 , RESULT2053
WHERE RESULT2053.SUB_CODE='CS501' AND RESULT2053.ROLLNO=STUDENT2053.ROLLNO AND (RESULT2053.MARKS>=70 AND RESULT2053.MARKS <=89);



iv.Find the student name, roll no who appeared in the examination for paper DBMS.
SELECT NAME, STUDENT2053.ROLLNO
 FROM STUDENT2053 , RESULT2053, SUBJECT2053
WHERE SUBJECT2053.SUBJECTNAME = 'Data Base Systems' AND SUBJECT2053.SUBJECTCODE=RESULT2053.SUB_CODE AND RESULT2053.ROLLNO=STUDENT2053.ROLLNO;

v.Show student names, subject code and marks for CSE 3rdyear students.
SELECT NAME, SUB_CODE , MARKS
FROM STUDENT2053, RESULT2053
WHERE STUDENT2053.SEMESTER='SEM5' AND STUDENT2053.DEPTCODE='CSE' AND STUDENT2053.ROLLNO=RESULT2053.ROLLNO;



vi.Show student names, department name for 5 th semester students who born in MAY.
SELECT NAME , DEPTNAME
FROM DEPARTMENT2053, STUDENT2053
WHERE STUDENT2053.SEMESTER='SEM5' AND EXTRACT(MONTH FROM STUDENT2053.BITHDATE)=5 AND STUDENT2053.DEPTCODE=DEPARTMENT2053.DEPTCODE;

vii.Show student names, subject name for 5thsemester student where subject name contains the word ‘DATA’
SELECT NAME, SUBJECTNAME
FROM STUDENT2053, SUBJECT2053
WHERE STUDENT2053.SEMESTER='SEM5' AND SUBJECT2053.SUBJECTNAME LIKE '%Data%' AND STUDENT2053.DEPTCODE=SUBJECT2053.DEPTCODE AND STUDENT2053.SEMESTER=SUBJECT2053.SEMESTER;


viii.Show student names, subject name and marks for 5thsemester students.
SELECT NAME, SUBJECTNAME, MARKS
FROM STUDENT2053, SUBJECT2053, RESULT2053
WHERE STUDENT2053.SEMESTER='SEM5' AND STUDENT2053.ROLLNO=RESULT2053.ROLLNO AND RESULT2053.SUB_CODE=SUBJECT2053.SUBJECTCODE;



ix.Find the roll number, student names and marks for CSE students who get more than 80 in Data Structure.
SELECT STUDENT2053.ROLLNO, NAME, MARKS
FROM STUDENT2053, RESULT2053 , SUBJECT2053
WHERE STUDENT2053.DEPTCODE='CSE' AND MARKS > 80 AND STUDENT2053.ROLLNO=RESULT2053.ROLLNO AND SUBJECT2053.SUBJECTNAME='Data Structure' AND RESULT2053.SUB_CODE=SUBJECT2053.SUBJECTCODE;



x.Show student names, department name, subject name and subject wise marks for which the student get more than 90.
SELECT NAME, DEPTNAME, SUBJECTNAME , MARKS
FROM STUDENT2053 , DEPARTMENT2053, SUBJECT2053, RESULT2053
WHERE MARKS > 90 AND STUDENT2053.ROLLNO = RESULT2053.ROLLNO AND STUDENT2053.DEPTCODE=DEPARTMENT2053.DEPTCODE AND RESULT2053.SUB_CODE=SUBJECT2053.SUBJECTCODE;

xi.Add column HOD in DEPARTMENT. Insert faculty id in place of HoD.
ALTER TABLE DEPARTMENT2053 ADD HOD VARCHAR2(4);
UPDATE DEPARTMENT2053 SET HOD = 'F01' WHERE DEPTCODE='CSE';
UPDATE DEPARTMENT2053 SET HOD = 'F02' WHERE DEPTCODE='ECE';
UPDATE DEPARTMENT2053 SET HOD = 'F03' WHERE DEPTCODE='IT';
UPDATE DEPARTMENT2053 SET HOD = 'F04' WHERE DEPTCODE='EE'; 

xii.Add column TEACHER in table SUBJECT. Insert faculty id in this column.
ALTER TABLE SUBJECT2053 ADD TEACHER VARCHAR2(4);
UPDATE SUBJECT2053 SET TEACHER = 'F01' WHERE SUBJECTCODE='CS301';
UPDATE SUBJECT2053 SET TEACHER = 'F02' WHERE SUBJECTCODE='CS302';
UPDATE SUBJECT2053 SET TEACHER = 'F03' WHERE SUBJECTCODE='CS501';
UPDATE SUBJECT2053 SET TEACHER = 'F04' WHERE SUBJECTCODE='CS502';
UPDATE SUBJECT2053 SET TEACHER = 'F05' WHERE SUBJECTCODE='ECS501';
UPDATE SUBJECT2053 SET TEACHER = 'F06' WHERE SUBJECTCODE='EC501';
UPDATE SUBJECT2053 SET TEACHER = 'F07' WHERE SUBJECTCODE='CS503';

xiii.Show the department name, semester, subject name along with faculty name.
SELECT DEPTNAME, SEMESTER, SUBJECTNAME, NAME
FROM SUBJECT2053 ,DEPARTMENT2053, FACULTY2053
WHERE SUBJECT2053.DEPTCODE=DEPARTMENT2053.DEPTCODE AND SUBJECT2053.TEACHER=FACULTY2053.FID;

xiv.Find the names of all faculties whose HOD name is given.
SELECT NAME , DEPARTMENT2053.DEPTNAME
FROM FACULTY2053, DEPARTMENT2053
WHERE FACULTY2053.FID = DEPARTMENT2053.HOD;


xv.Display subject name, subject code, marks including all subjects. [Outer join ]
SELECT SUBJECT2053.SUBJECTNAME, SUBJECT2053.SUBJECTCODE, RESULT2053.MARKS
FROM SUBJECT2053
LEFT OUTER JOIN RESULT2053
ON SUBJECT2053.SUBJECTCODE=RESULT2053.SUB_CODE;

xvi.Display students name, subject code, marks. Include all students. [Outer join ]
SELECT STUDENT2053.NAME, RESULT2053.SUB_CODE, RESULT2053.MARKS
FROM STUDENT2053
LEFT OUTER JOIN RESULT2053
ON STUDENT2053.ROLLNO=RESULT2053.ROLLNO;




i. Display name, phone number of students with ‘a’ as the second letter in their names who read subject CS301.
SELECT NAME,PHONENO FROM Student2053 WHERE NAME LIKE '_A%' AND ROLLNO IN (SELECT ROLLNO FROM Result2053 WHERE SUB_CODE='CS301');


ii. Display the marks for all available subjects for the students who born in JUNE.
SELECT MARKS FROM Result2053 WHERE ROLLNO IN (SELECT ROLLNO FROM Student2053 WHERE EXTRACT(MONTH FROM BITHDATE)=6);

iii. Show the student details of 5th semester Computer science and engineering Department.
SELECT * FROM Student2053 WHERE SEMESTER='SEM5' AND DEPTCODE IN (SELECT DEPTCODE FROM DEPARTMENT2053 WHERE DEPTNAME='Computer Science and Engineering');

iv. Show the subject details of 3rd semester Computer science and engineering Department.
SELECT * FROM Subject2053 WHERE SEMESTER ='SEM3' AND DEPTCODE IN (SELECT DEPTCODE FROM DEPARTMENT2053 WHERE DEPTNAME='Computer Science and Engineering');



v. Display the department name for which some student get more than 90.
SELECT DEPTNAME FROM DEPARTMENT2053 WHERE DEPTCODE IN (SELECT DEPTCODE FROM Student2053 WHERE ROLLNO IN (SELECT ROLLNO FROM Result2053 WHERE MARKS>90));

vi. Display the student name who reads in 5th semester and get more than 80 in any subject.
SELECT NAME FROM Student2053 WHERE SEMESTER='SEM5' AND ROLLNO IN (SELECT ROLLNO FROM Result2053 WHERE MARKS > 80);

vii. Display the name of CSE student who born in 2000 and get more than 80 in CS301.
SELECT NAME FROM Student2053 WHERE DEPTCODE='CSE' AND EXTRACT(YEAR FROM BITHDATE)=2000 AND ROLLNO IN (SELECT ROLLNO FROM Result2053 WHERE MARKS > 80 AND SUB_CODE='CS301');

viii. Display the department details with less than 80 students which has subject name Data Communication.
SELECT * FROM DEPARTMENT2053 WHERE STUDENTALLOTTED < 80 AND DEPTCODE IN (SELECT DEPTCODE FROM Subject2053 WHERE SUBJECTNAME='Data Communication');


ix. Display subject name, subject code of the department with allotted student less than 100.
SELECT SUBJECTNAME,SUBJECTCODE FROM Subject2053 WHERE DEPTCODE IN (SELECT DEPTCODE FROM DEPARTMENT2053 WHERE STUDENTALLOTTED < 100);

x. Show Roll number, subject code and marks for CSE 3rd year students where subject name starts with D.
SELECT ROLLNO,SUB_CODE,MARKS FROM Result2053 WHERE ROLLNO IN (SELECT ROLLNO FROM Student2053 WHERE (SEMESTER='SEM5' OR SEMESTER='SEM6') AND DEPTCODE='CSE') AND SUB_CODE IN (SELECT  SUBJECTCODE FROM Subject2053 WHERE SUBJECTNAME LIKE 'D%');

xi. Display roll number, subject and marks of students who took admission in the year 2017 and read subject CS505.
SELECT ROLLNO,SUB_CODE,MARKS FROM Result2053 WHERE SUB_CODE='CS505' AND ROLLNO IN (SELECT ROLLNO FROM Student2053 WHERE YEAROFADM=2017);


xii. Find the student details of CSE students whose marks are not available in result.
SELECT * FROM Student2053 WHERE DEPTCODE='CSE' AND ROLLNO NOT IN (SELECT ROLLNO FROM Result2053);

xiii. Find the subject name, subject code which is not included in result.
SELECT SUBJECTNAME,SUBJECTCODE FROM Subject2053 WHERE SUBJECTCODE NOT IN (SELECT DISTINCT SUB_CODE FROM Result2053);




